Lesson3 homework
javascript-163/AnkaBagishvili pull request #3
Opened 2024-01-26 17:49 UTC by AnkaBagishvili

2024-01-28 23:42 UTC, Michael-Malania requested changes
გადახედე კომენტარებს

2024-01-28 23:42 UTC, Michael-Malania commented on Lesson3Homework/script.js
> +let temp = prompt("Enter Degree Celsius");
აქ კარგი ინქებოდა შეგექმნა ფუნქცია, რომელშიც გათვალისწინებული იქნებოდა მომხმარებლის არჩევანი, რომ შეგეთავაზებინა თუ რა ერჩივნა ცელსიუსიდან ფარენჰეიტში თუ პირიქით კონვერტირება

2024-01-28 23:42 UTC, Michael-Malania commented on Lesson3Homework/script.js
> +
აქ კომენტარის სახით რომ დაამატო ამოცანის პირობა კარგი იქნება სამომავლოდ რომ გაითვალისწინო

2024-01-28 23:42 UTC, Michael-Malania commented on Lesson3Homework/script.js
> +if (chooseYear % 4 === 0) {
ესე ვერ გაიგებ ზუსტად წელიწადი ნაკიანია თუ არაა მხოლოდ 4-ზე უნაშთოდ გაყოფის შემოწმება არ ყოფნის

2024-01-29 12:26 UTC, AnkaBagishvili reviewed
შესწორებული ვარიანტი ))

პს წინა დავალებაც რომ ნახოთ,ბარემ...

2024-02-03 18:57 UTC, closed without merging